### ISSUE TITLE
Windows compiler I/O error

### ISSUE THREAD

**Issue by bencompton** [phenomejs/phenome#35]
When attempting  to run `npm run build-test`, the following error occurs in Windows:

```
{ Error: Could not resolve './runtime-helpers
                                             ue-component-get-props.js' from test\component-library\dist\vue\app.js
    at error (C:\git\universal-component\node_modules\rollup\dist\rollup.js:170:15)
    at C:\git\universal-component\node_modules\rollup\dist\rollup.js:19580:25
    at <anonymous> code: 'UNRESOLVED_IMPORT' }
TypeError: Cannot read property 'generate' of undefined
    at buildBundle (C:\git\universal-component\test\build.js:53:18)
    at <anonymous>
```

Since Windows uses `\` to delimit paths, there's a conflict somewhere in the compiler I/O that is causing the Windows-style paths and `nix style paths to get mixed together. This issue does not occur in macOS, and I assume Linux.

**Comment by nolimits4web** [comment]
Looks like here https://github.com/phenomejs/phenome/blob/master/src/compilers/compiler-utils/compiler-state.js#L26

Issue was because when we imported helpers we didn’t do it relatively to component file. I was trying to get relative path using Node path util but didn’t figure out how to make it work correctly when helpers folder is in the same folder as components, like we have now

**Comment by nolimits4web** [comment]
I mean by default it doesn’t add “./“ to the beginning
